name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies with uv
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv sync

    - name: Lint with flake8
      run: |
        source .venv/bin/activate
        flake8 .

    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest
